name: flutter_plugin_tools

description: Productivity utils for hosting multiple plugins within one repository.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugin_tools
version: 0.0.1

dependencies:
  args: "^0.13.7"
  path: "^1.4.1"
  http: "^0.11.3+13"

environment:
  sdk: ">=1.8.0 <2.0.0"
